### ISSUE TITLE
Possible set of parameters

### ISSUE THREAD

**Issue by torwag** [JFK20/ha-draw#6]
Taken that tldraw drawings will have potentially a lot of mappings to and from entities, I feel it is important to get clear about the config parameters.
 
1. We have to keep into account that the card is only updated whenever there are value changes for entities in the entity section. HA doesn't update the card, if e.g. values change for entities which are used in templates (see #5)
2. As we might want to redraw an object based on multiple entity changes, we can use groups, which bind a set of entities to particular actions.
3. We need a custom set of parameters for tldraw to map the tldraw objects to the entities.
4. I would suggest making it as generic and hence as flexible as possible, leaving it to the user (and the documentation) to deal with the different possible tldraw parameters.

A possible parameter set could look like:
(just a mockup with fake values here and there)
```
type: custom:tldraw-react-ha
groups:
  - entities:
      - sensor.temperature1
      - sensor.temperature2
    template: >
      {{ (states(sensor.temperature1) | float - states(sensor.temperature2) | float }},
    tldraw:
      id: delta_temperature_text_box
      parameter: value
      valuetype: absolute
      on_error: previous
  - entities:
      - sensor.temp3
      - sensor.temp4
    template: >
      {% if states('sensor.temp3') | float > 25 or states('sensor.temp4') | float > 25 or states('sensor.temp5') | float > 25 %}
         red
      {% else %}
         green
      {% endif %}
    tldraw:
      id: temp_alarm_circle
      parameter: fill
      valuetype: absolute
      on_error: "gray"
```
All entities in the entities section will be monitored and the card-update will be triggered whenever a value change happens, this gives us fine control when an update should occur for muliple entities, as in example 2 it will only be called if there are changes to temp3 and temp4 albeit if triggered also temp5 will be checked.
 
The template entry defines what should be send to the tldraw object. We could make this mandatory, or if not given, we could e.g. return the value of all entities as a list (not very practical but maybe nice for debugging). Within the template we can take care of min, max values, of conversions, rounding, of mapping with strings, etc. Other helpers within HA can be used to deal with statistic values. 

The tldraw group will include everything we need to know to manipulate an object of the tldraw canvas.
- ``id``: is the id of the tldraw-object which we want to map
- ``parameter``: is the parameter we want to change (this could be any parameter the object has, including the shape itself)
- ``valuetype``: if set to ``absolute`` the new value will replace the old value, if set to ``relative``, the new value will be added to the old value
- ``on_error``: what should be set if the template returns an error, an empty value or ``not defined`` value. As this can happen quite often if entity states are of value ``not defined``, it will simplify templates a lot, as we do not have to check for this within templates itself. Possible values are whatever make sense with the special value "previous" to make sure that in that case the old value should remain unchanged.

The logic behind this would look like this:

1. one of the entity triggers a value change event.
2. the tldraw object gets read in with all parameters
3. the template gets executed
4. the given parameter gets updated according to the template return value, the valuetype and on_error setting
5. trigger a redraw within tldraw with the new object parameters.

**Comment by torwag** [comment]
This obviously would be an n-1 mapping, multiple entities can modify one tldraw parameter, a 1-n or n-n could be archived by replicating the groups for each tldraw parameter. This is rather verbose but should work out of the box. We might later want to allow a list of objects to shorten this.
```
...
tldraw:
      - id: temp_alarm_circle1
          parameter: fill
          valuetype: absolute
          on_error: "gray"
      - id: temp_alarm_circle2
          parameter: fill
          valuetype: absolute
          on_error: "gray"
```
